definitions:
  model.Goal:
    properties:
      createdAt:
        type: string
      deadline:
        type: string
      description:
        type: string
      id:
        type: string
      priority:
        type: integer
      status:
        type: string
      tasks:
        additionalProperties:
          type: boolean
        type: object
      title:
        type: string
      updatedAt:
        type: string
      user:
        $ref: '#/definitions/model.User'
      userID:
        type: string
    type: object
  model.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      goal:
        items:
          $ref: '#/definitions/model.Goal'
        type: array
      id:
        type: string
      password:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/getallusers:
    get:
      description: Retrieve a list of all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: Get all users
      tags:
      - Users
swagger: "2.0"
